# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 이상호
title: Java Back-End Developer
email: lovethefeel@gmail.com
web: https://lovethefeel.tistory.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  codeleesh

# Additional icon links
additional_links:
  - title: Blog
    icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
    url: https://lovethefeel.tistory.com

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. Java & Spring 기반의 7년차 백엔드 개발자로 금융권 마이데이터 플랫폼, 실험실 정보 관리 시스템(LIMS), 은행권 OPEN API, 부가인증(OTP) 관리 시스템, 계정 권한 관리 시스템 등의 서비스에서 API 개발 및 서버 구축을 해왔습니다.<br />
  현재는 내부에서 마이데이터 플랫폼 개발을 진행하고 있으며 특히 원활한 테스트를 위해서 가상 테스트 베드를 개발하여 개인 자산 수집 테스트, 시나리오 테스트 등을 맡아서 개발하고 있습니다.<br />
  작은 것 하나라도 메모하는 것의 중요성을 깨달아 실천하기 위해서 매일 회사와 집에서 각각 일지를 쓰면서 필요한 내용은 컨플루언스와 블로그에 작성하여 공유하고 있습니다.<br />
  테스트 코드의 중요성을 통해 기존 프로젝트의 테스트 코드가 존재하지 않았지만 테스트 커버리지 80% 달성하기 위해 노력중입니다.<br />

content:
  - title: 경력
    layout: list
    content:
      - layout: left
        title: 에스코어
        link: https://www.s-core.co.kr
        sub_title: Java & Spring 백엔드 개발자
        caption: 2021.07 ~ 현재
        quote: >
          마이데이터 플랫폼 개발
        description: |
          - 금융보안원 표준 API 1.0 버전 적용
          - 가상 금융 데이터 수집 테스를 위한 테스트베드 백엔드 개발
          - 데모 테스트를 위한 앱템플릿 백엔드 개발
          - Spring WebFlux을 이용한 API 서버 호출 개발

      - layout: left
        title: 마크로젠
        link: https://www.macrogen.com
        sub_title: Java & Spring 백엔드 개발자
        caption: 2019.08 ~ 2021.06
        quote: >
          사내 프로젝트 실험실 관리 시스템 국내 및 해외법인(일본, 미국) API 개발 및 구축 진행
        description: |
          - 사내 프로젝트 실험실 관리 시스템 고도화
          - 해외법인(일본, 미국) 실험실 관리 시스템 고도화
          - 국내와 법인간 아웃소싱 주문을 위한 API 통신 처리
          - 전자정부 프레임워크, MyBatis, Oracle 환경에서의 개발 경험

      - layout: left
        title: 프리커스
        link: http://precursor.co.kr
        sub_title: Java & Spring 백엔드 개발자
        caption: 2014.02 ~ 2019.07
        quote: >
          계정 / 권한 관리 시스템, 부가인증(OTP) 관리 시스템, 오픈 API 백엔드 개발
        description: |
          - MAU 1만, MAU 14만 계정 / 권한 관리 시스템 개발
          - 전자정부 프레임워크, MyBatis, Oracle 환경에서의 개발 경험

  - title: 스킬
    layout: list
    content:
      - layout: left
        title: BackEnd
        description: |
          - Java
          - Spring Boot, Spring MVC, Sptring Data JPA, Spring Webflux
          - JPA, Querydsl, Hibernate
          - Junit4/5, Mockito
          - Gradle, Maven
          - IntelliJ

      - layout: left
        title: DevOps
        description: |
          - MySQL, PostgreSQL
          - Jenkins, Git-runner
          - Weblogic, Netty, Tomcat
          - JMeter, Postman
          - Centos, Ubuntu

  - title: 교육
    layout: list
    content:
      - layout: left
        title: 넥스트스텝
        link: https://edu.nextstep.camp
        caption: 2021.11 ~ 2022.12
        quote: >
          우아한테크캠프 Pro 3기
        description: |
          - JPA 기반 웹 어플리케이션 개발
          - 단위, 인수테스트 기반 개발
          - 레거시 코드를 안정적으로 리팩토링하는 경험

      - layout: left
        title: 인프런
        런ink: https://www.inflearn.com
        caption: 2022.01 ~ 현재
        quote: >
          백엔드 개발자로 필요한 역량을 채우기 위해 교육 학습
        description: |
          - 모든 개발자를 HTTP 웹 기본 지식
            - HTTP 웹 기본 지식 내용 정리
          -

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
